name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.10.13
  - seaborn=0.12.2
  - pandas=1.5.3
  - numpy=1.24.3
  - matplotlib=3.7.1
  - wordcloud=1.9.3
  - umap-learn=0.5.5
  - scikit-learn=1.3.0
  - nltk
  - jupyter
  - make
  - git
