name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.10.13
  - seaborn=0.13.2
  - pandas=2.1.4
  - numpy=1.26.3
  - matplotlib=3.8.2
  - wordcloud=1.9.3
  - umap-learn=0.5.5
  - scikit-learn=1.4.0
  - nltk=3.8.1
  - jupyter=1.0.0
  - make
  - git
